### ISSUE TITLE
Cannot get an OpenTelemetry SDK connection before the SDK is initialized

### ISSUE THREAD

**Issue by mspatagundi7** [rickbansal-mulesoft/otel-mule4-observability-agent#14]
Hello Rick,

Initially we were using version 1.0.2 to send traces to Dynatrace and was working fine with Cloudhub deployment. After the recent update you had did, we had downloaded latest 1.3.0 version and updated the connector configuration accordingly. But when we deploy our api to Cloudhub environment with this new version of plugin, the traces are not being sent to Dynatrace, getting error **Cannot get an OpenTelemetry SDK connection before the SDK is initialized**. PFA for Detailed error log.
But when we test the api with plugin version 1.3.0 from our local Anypoint studio, able to send the traces to Dynatrace.
We are unable to figure the issue, tried different options, could you please help on this.

Please let me know if needed any other details.

[OpenTelemetry version 1.3.0 issue.txt](https://github.com/rickbansal-mulesoft/otel-mule4-observability-agent/files/14053677/OpenTelemetry.version.1.3.0.issue.txt)

Thanks,
Mahaninga S Patagundi

**Comment by mspatagundi7** [comment]
Hello @rickbansal-mulesoft,

Could you please look into this issue whenever you have sometime and help us.

Thanks,
Mahaninga S Patagundi

**Comment by rickbansal-mulesoft** [comment]
Hi, might need to set up a time early next week where you can show me how
you're configured.  Please provide some date/time options that work for
you.  Thanks.

**Comment by mspatagundi7** [comment]
Hello @rickbansal-mulesoft ,

Sorry for the late reply, please confirm is that be fine if I setup a call at 10 to 11AM CST tomorrow(Tuesday). If it is conflict for you Please suggest some time based on your calendar availability.

Thanks,
Mahaninga S Patagundi

**Comment by rickbansal-mulesoft** [comment]
Yes, 10am CT will work.  Thanks.

**Comment by mspatagundi7** [comment]
Thank you. I will send an invite.

Thanks,
Mahaninga

**Comment by mspatagundi7** [comment]
Hi @rickbansal-mulesoft ,

Thank you so much for your kind help, we are able to send the traces to Dynatrace along with queryParams as well now.

As you suggested to deploy api directly from Studio, we had deployed and later compared the dependencies that packaged with the jar that built through pipeline and deployed through Studio, found that few Opentelemetry related jars (Looks those extra jars were needed for latest version of plugin) were missing when built through pipeline. After adding those dependencies in pom.xml, now through pipeline also api is building successfully and able to send trace as well.

Thanks,

Mahaninga
