### ISSUE TITLE
Logger issue

### ISSUE THREAD

**Issue by bijuiv-ms** [rickbansal-mulesoft/otel-mule4-observability-agent#3]
When using Logger message processor, the otel agent is augmenting the event payload with the message extracted from the Logger. So any subsequent message processors in the flow that's acting on the payload (ex:Transform Message) starts erroring out because of the modified payload. Tested after removing the otel agent dependency and then the flow works normally. So just by adding the otel dependency (even without setting the connector config), it starts corrupting the payload when there's a Logger message processor in the flow.

**Comment by rickbansal-mulesoft** [comment]
Should be fixed in the latest version of the extension - 1.0.1

**Comment by bijuiv-ms** [comment]
Thanks, this is resolved now.
